version: "3"
networks:
  store_network:
    driver: bridge
services:
  django: &django
    build:
      context: .
      dockerfile : ./compose/local/django/Dockerfile
    container_name: store-django
    image: store-local-image
    depends_on:
      - postgresql
      - redis

    volumes:
      - .:/app:z
    networks:
      - store_network
    env_file : 
      - ./.envs/secrets_local.env
      - ./.envs/.postgres
      - ./.envs/.django

    ports:
      - '8000:8000'

    command : /start

  postgresql :
      image: postgres:alpine
      container_name: store_postgresDatabase
      ports:
        - "5432:5432"
      env_file:
        - ./.envs/.postgres
      networks:
        - store_network
      volumes:
        - postgres_data:/var/lib/postgresql/data

  redis:
    image: "redis:alpine"
    env_file:
    - ./.envs/.redis
    container_name: redis_contianer
    networks:
    - store_network
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  celeryworker:
    <<: *django
    image: celery_worker
    container_name: celery_worker
    networks:
      - store_network
    depends_on:
      - redis
      - postgresql
    ports: []
    command: /start-celeryworker


volumes:
    postgres_data:
    redis_data:
