version: "3"
networks:
  ola_network:
    driver: bridge
services:
  django: &django
    build:
      context: .
      dockerfile : ./compose/local/django/Dockerfile
    container_name: olastore-django
    image: olastore-local-image
    depends_on:
      - postgresql
      - redis

    volumes:
      - .:/app:z
    networks:
      - ola_network
    env_file : 
      - ./.envs/secrets_local.env
      - ./.envs/.postgres
      - ./.envs/.django

    ports:
      - '8000:8000'

    command : /start

  postgresql :
      image: postgres:latest
      container_name: olastore_postgres_data
      ports:
        - "5432:5432"
      env_file:
        - ./.envs/.postgres
      networks:
        - ola_network
      volumes:
        - postgres_data:/var/lib/postgresql/data
  redis:
    image: "redis:latest"
    env_file:
    - ./.envs/.redis
    container_name: ola_store_reids_container
    networks:
    - ola_network
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
volumes:
    postgres_data:
    redis_data:
