# Generated by Django 5.0.6 on 2024-06-09 09:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('category_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=200)),
                ('picture', models.ImageField(upload_to='CategoryImages/')),
                ('active', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('product_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_title', models.CharField(max_length=500)),
                ('product_description', models.TextField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available_sizes', models.CharField(default='S', max_length=100)),
                ('material', models.CharField(blank=True, default='N/A', max_length=50, null=True)),
                ('available_colors', models.CharField(default='N/A', max_length=100)),
                ('product_instock', models.BooleanField(default=True)),
                ('discount_available', models.BooleanField(default=False)),
                ('picture', models.ImageField(upload_to='ProductImages/')),
                ('category_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='src_products.category')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'db_table': 'products',
            },
        ),
    ]
