# Generated by Django 4.2.10 on 2024-03-23 13:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('src_products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('0f7092ea-7c4d-47bc-b9cf-e13bbf66a511'), editable=False, primary_key=True, serialize=False),
        ),
    ]
