# Generated by Django 4.2.10 on 2024-02-29 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src_products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_info',
            field=models.JSONField(default=dict),
        ),
    ]
