# Generated by Django 4.2.10 on 2024-03-23 13:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('src_products', '0002_alter_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('f9c7108d-be3b-4f66-966d-17deaa7c8e39'), editable=False, primary_key=True, serialize=False),
        ),
    ]
