# Generated by Django 4.2.10 on 2024-03-24 03:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('src_products', '0003_alter_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('74124906-9ddf-456f-b86e-2aa8077c1748'), editable=False, primary_key=True, serialize=False),
        ),
    ]
