# Generated by Django 4.2.10 on 2024-03-24 03:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('src_products', '0004_alter_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('92abbca2-fd16-48b7-913d-7def12a4987e'), editable=False, primary_key=True, serialize=False),
        ),
    ]
