# Generated by Django 4.2.10 on 2024-02-22 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src_users', '0002_remove_user_user_id_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('valid_untill', models.DateTimeField()),
            ],
        ),
    ]
