# Generated by Django 5.0 on 2024-01-27 22:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("src_users", "0003_user_verified_alter_user_username_paymentinformation"),
    ]

    operations = [
        migrations.RenameField(
            model_name="paymentinformation",
            old_name="customer",
            new_name="user",
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("profilePicture", models.ImageField(upload_to="Customerimages/")),
                (
                    "paymentInformation",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="src_users.paymentinformation",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=255)),
                ("business_registration_id", models.CharField(max_length=50)),
                ("tax_id", models.CharField(max_length=20)),
                ("company_email", models.EmailField(max_length=254)),
                ("company_phone_number", models.CharField(max_length=15)),
                ("payment_history", models.TextField()),
                ("invoices", models.TextField()),
                ("store_description", models.TextField()),
                ("store_policies", models.TextField()),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
