# Generated by Django 5.0 on 2024-01-27 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("src_address", "__first__"),
        ("src_users", "0004_rename_customer_paymentinformation_user_customer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="address",
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="src_address.address",
            ),
        ),
    ]
