# Generated by Django 5.0 on 2024-01-27 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("src_address", "__first__"),
        ("src_users", "0005_customer_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="address",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="src_address.address"
            ),
        ),
    ]
