# Generated by Django 4.2.10 on 2024-02-22 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_emailaddress_idx_upper_email'),
        ('src_users', '0006_alter_otp_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='email',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.emailaddress'),
        ),
    ]
