# Generated by Django 4.2.10 on 2024-02-23 03:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("src_users", "0008_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(db_index=True, max_length=25),
        ),
    ]
