# Generated by Django 4.2.10 on 2024-04-12 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src_address', '0002_initial'),
        ('src_users', '0009_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('business_registration_id', models.CharField(max_length=50)),
                ('tax_id', models.CharField(max_length=20)),
                ('company_email', models.EmailField(max_length=254)),
                ('company_phone_number', models.CharField(max_length=15)),
                ('payment_history', models.TextField()),
                ('invoices', models.TextField()),
                ('store_description', models.TextField()),
                ('store_policies', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(blank=True, max_length=16, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('cvv', models.CharField(blank=True, max_length=4, null=True)),
                ('billing_address', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profilePicture', models.ImageField(upload_to='Customerimages/')),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='src_address.address')),
                ('paymentInformation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='src_users.paymentinformation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
