# Generated by Django 5.0.6 on 2024-06-09 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('src_address', '0003_rename_src_address_user_id_4f5b17_idx_addresses_user_id_85e7e9_idx_and_more'),
        ('src_products', '0001_initial'),
        ('src_users', '0012_delete_paymentinformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('payment', models.CharField(choices=[('on_delivery', 'On Delivery'), ('online', 'Online')], max_length=20)),
                ('order_number', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quantity', models.IntegerField()),
                ('discount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('ship_date', models.DateField()),
                ('delivered', models.BooleanField(db_index=True, default=False)),
                ('size', models.CharField(blank=True, choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL'), ('XXXXL', 'XXXXL')], default='N/A', max_length=10, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src_users.customer')),
                ('order_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src_address.address')),
                ('products', models.ManyToManyField(to='src_products.product')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'db_table': 'orders',
            },
        ),
    ]
