# Generated by Django 5.0 on 2023-12-23 21:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "address_ID",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("effective_date", models.DateField()),
                (
                    "address_type",
                    models.CharField(
                        choices=[
                            ("billing", "Billing"),
                            ("home", "Home"),
                            ("office", "Office"),
                        ],
                        max_length=20,
                    ),
                ),
                ("address_line_1", models.CharField(max_length=255)),
                (
                    "address_line_2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("city", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
                ("zip_code", models.CharField(max_length=20)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user"], name="src_address_user_id_4f5b17_idx"
                    ),
                    models.Index(
                        fields=["effective_date"], name="src_address_effecti_75c516_idx"
                    ),
                    models.Index(
                        fields=["address_type"], name="src_address_address_2c8bf1_idx"
                    ),
                    models.Index(
                        fields=["country"], name="src_address_country_dd2fd8_idx"
                    ),
                    models.Index(
                        fields=["zip_code"], name="src_address_zip_cod_76126d_idx"
                    ),
                ],
            },
        ),
    ]
