# Generated by Django 5.0.6 on 2024-06-05 15:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("src_address", "0002_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="address",
            new_name="Addresses_user_id_85e7e9_idx",
            old_name="src_address_user_id_4f5b17_idx",
        ),
        migrations.RenameIndex(
            model_name="address",
            new_name="Addresses_effecti_1671aa_idx",
            old_name="src_address_effecti_75c516_idx",
        ),
        migrations.RenameIndex(
            model_name="address",
            new_name="Addresses_address_823e20_idx",
            old_name="src_address_address_2c8bf1_idx",
        ),
        migrations.RenameIndex(
            model_name="address",
            new_name="Addresses_country_e67afc_idx",
            old_name="src_address_country_dd2fd8_idx",
        ),
        migrations.RenameIndex(
            model_name="address",
            new_name="Addresses_zip_cod_f769d3_idx",
            old_name="src_address_zip_cod_76126d_idx",
        ),
        migrations.AlterModelTable(
            name="address",
            table="Addresses",
        ),
    ]
