# Generated by Django 5.0 on 2023-12-23 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("src_address", "0002_alter_address_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="country",
            field=models.CharField(max_length=100),
        ),
    ]
